Repository Bandnol/Bandnol-Front, pull requests merged in 2025-08, with the labels that each got.

#34 FEAT/#33 음악 검색 API 기능 연동
  .env.d.ts
  api/aiRecommend.ts
  api/sendReply.ts
  api/spotifySearch.ts
  app/(tabs)/music-recommend/searchMusic.tsx
  app/(tabs)/music-recommend/sendRecommend.tsx
  package.json
  yarn.lock
Labels: API, 이즈

#35 UI/#23 추천곡 배경 수정 및 위치 조정
  app/(onboarding)/step1-personal.tsx
  app/(tabs)/music-recommend/myRecommend.tsx
  app/(tabs)/music-recommend/receiveRecommend.tsx
  babel.config.js
  package.json
  yarn.lock
Labels: Design, 무니

#42 Feat/#41 음악 추천 발신 api 연동
  api/aiRecommend.ts
  api/postReplyAsRecoms.ts
  api/replies.ts
  api/sendReply.ts
  app/(tabs)/music-recommend/myRecommend.tsx
  app/(tabs)/music-recommend/sendRecommend.tsx
  yarn.lock
Labels: API, 이즈

#43 Feat/#38 아티스트 목록 컴포넌트
  app/(auth)/inquiry.tsx
  app/(onboarding)/step1-personal.tsx
  app/(onboarding)/step2-artist.tsx
  app/(onboarding)/step3-timesetting.tsx
  app/(tabs)/myPage/setting/appSetting.tsx
  app/(tabs)/myPage/setting/userInfo.tsx
  app/(tabs)/mypage.tsx
  components/common/InterestedArtistList.tsx
  components/common/RecommendedArtistList.tsx
  hooks/useSocialAuth.ts
  package.json
  store/api.ts
  store/auth.ts
  yarn.lock
Labels: Feature, 오즈

#45 Fix/#40 UI detail
  app/(tabs)/music-recommend/alarmCenter.tsx
  app/(tabs)/recommend-tab/RecSearch.tsx
  app/(tabs)/recommend-tab/RecShareModal.tsx
  app/(tabs)/recommend-tab/RecommendCal.tsx
  components/NotificationItem.tsx
  package.json
  yarn.lock
Labels: Design, 보현

#49 Feat/#38 artist api 연동
  android/app/src/main/java/com/bandnol/Bandnol/MainActivity.kt
  android/app/src/main/java/com/bandnol/Bandnol/MainApplication.kt
  android/app/src/main/res/drawable-hdpi/splashscreen_logo.png
  android/app/src/main/res/drawable-mdpi/splashscreen_logo.png
  android/app/src/main/res/drawable-xhdpi/splashscreen_logo.png
  android/app/src/main/res/drawable-xxhdpi/splashscreen_logo.png
  android/app/src/main/res/drawable-xxxhdpi/splashscreen_logo.png
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values-night/colors.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  app.config.ts
  app/(onboarding)/step2-artist.tsx
  app/(tabs)/myPage/setting/appSetting.tsx
  app/(tabs)/myPage/setting/userInfo.tsx
  babel.config.js
  components/Collapsible.tsx
  components/ThemedText.tsx
  components/ThemedView.tsx
  hooks/useAuthFetch.tsx
  hooks/useSocialAuth.ts
  hooks/useThemeColor.ts
  ios/Bandnol.xcodeproj/project.pbxproj
  ios/Bandnol/Images.xcassets/SplashScreenBackground.colorset/Contents 2.json
  ios/Bandnol/Images.xcassets/SplashScreenLogo.imageset/Contents 2.json
  ios/Bandnol/Images.xcassets/SplashScreenLogo.imageset/image 2.png
  ios/Bandnol/Images.xcassets/SplashScreenLogo.imageset/image@2x 2.png
  ios/Bandnol/Images.xcassets/SplashScreenLogo.imageset/image@3x 2.png
  ios/Bandnol/Info.plist
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Feature, API, 오즈

#51 UI/#46 온보딩 뒤로가기 모달
  app/(onboarding)/step1-personal.tsx
  components/common/StatusBarHeader.tsx
Labels: Design, 이즈

#57 Feat/#52 reply fetch api
  api/replies.ts
  app/(tabs)/music-recommend/myRecommend.tsx
Labels: API, 이즈

#59 FEAT: 설정/알림 API 연동
  app/(tabs)/myPage/setting/appSetting.tsx
  app/(tabs)/myPage/setting/notification.tsx
Labels: API, 이즈

#60 Feat/#47 코멘트 조회 API 연동
  app.config.ts
  app/(auth)/inquiry.tsx
  app/(auth)/login.tsx
  app/(auth)/splash.tsx
  app/(onboarding)/step2-artist.tsx
  app/(onboarding)/step3-timesetting.tsx
  app/(onboarding)/step4-done.tsx
  app/(tabs)/music-recommend/alarmCenter.tsx
  app/(tabs)/music-recommend/myRecommend.tsx
  app/(tabs)/music-recommend/receiveRecommend.tsx
  app/(tabs)/music-recommend/sendRecommend.tsx
  app/(tabs)/myPage/follow-status/followEachOther.tsx
  app/(tabs)/myPage/follow-status/followedByOther.tsx
  app/(tabs)/myPage/follow-status/followingOnlyOther.tsx
  app/(tabs)/myPage/follow-status/notFollowingEachOther.tsx
  app/(tabs)/myPage/myPage.tsx
  app/(tabs)/myPage/myPageSearch.tsx
  app/(tabs)/myPage/setting/appSetting.tsx
  app/(tabs)/myPage/setting/receiveTime.tsx
  app/(tabs)/myPage/setting/userInfo.tsx
  app/(tabs)/post-tab/PostFilterModal.tsx
  app/(tabs)/post.tsx
  app/(tabs)/postWrite.tsx
  app/(tabs)/recommend-tab/RecBottomModal.tsx
  app/(tabs)/recommend-tab/RecSearch.tsx
  app/(tabs)/recommend-tab/RecShareModal.tsx
  app/(tabs)/recommend-tab/RecommendCal.tsx
  app/(tabs)/recommend-tab/RecommendHeader.tsx
  app/(tabs)/recommend-tab/RecommendList.tsx
  app/(tabs)/recommend.tsx
  app/_layout.tsx
  app/index.tsx
  components/Group1.tsx
  components/MonthPicker.tsx
  components/NotificationItem.tsx
  components/common/BottomNextButton.tsx
  components/common/ConfirmModal.tsx
  components/common/InterestedArtistList.tsx
  components/common/RecommendedArtistList.tsx
  components/common/onboarding-modal.tsx
  hooks/useUpdateOwnId.ts
  package-lock.json
  store/api.ts
  types/svg.d.ts
  yarn.lock
Labels: API, 무니

#67 FIX: UI 피드백 수정
  app/(tabs)/myPage/myPage.tsx
  components/common/ModalPopup.tsx
Labels: Fix, 이즈

#65 FIX: 바텀바 반응형 만들기
  app/(tabs)/music-recommend/searchMusic.tsx
  components/common/BottomTabBar.tsx
Labels: Fix, 이즈

#63 Fix/#62 list api fix
  app/(tabs)/music-recommend/receiveRecommend.tsx
  app/(tabs)/myPage/myPage.tsx
  app/(tabs)/post.tsx
  app/(tabs)/recommend-tab/RecBottomModal.tsx
  app/(tabs)/recommend-tab/RecShareModal.tsx
  app/(tabs)/recommend-tab/RecommendCal.tsx
  app/(tabs)/recommend.tsx
  ios/Bandnol.xcodeproj/project.pbxproj
  ios/Podfile.lock
Labels: Fix, API, 보현

#61 Feat/#48-3차과제 시연 영상 ver
  api/aiRecommend.ts
  api/spotifySearch.ts
  app.config.ts
  app/(onboarding)/step1-personal.tsx
  app/(onboarding)/step2-artist.tsx
  app/_layout.tsx
  app/artist/[artistId].tsx
  app/index.tsx
  components/common/InterestedArtistList.tsx
  components/common/RecommendedArtistList.tsx
  hooks/useAxios.tsx
  hooks/usePushNotification.ts
  hooks/useSocialAuth.ts
  ios/Bandnol.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Fix, API, 오즈

#97 Fix/#95 안드 텍스트 잘림 & 젠더 버튼 반응형
  app/(auth)/inquiry.tsx
  app/(onboarding)/step1-personal.tsx
  app/(tabs)/myPage/setting/userInfo.tsx
  app/(tabs)/post.tsx
  app/(tabs)/recommend-tab/RecShareModal.tsx
Labels: Fix, 보현

#93 FIX: 안드 모달 이모지 잘림 현상 해결
  app/(tabs)/myPage/setting/receiveTime.tsx
  components/common/ModalPopup.tsx
Labels: Fix, Design, 이즈

#101 FIX: 상단탭 제거
  app/_layout.tsx
Labels: Fix, Design, 이즈

#99 FIX: 좋아요 토스트 UI 구현
  app/(tabs)/music-recommend/receiveRecommend.tsx
  components/common/BottomToast.tsx
Labels: Design, 무니

#107 UI: 디자인 QA 수정
  app/(tabs)/music-recommend/myRecommend.tsx
  app/(tabs)/music-recommend/receiveRecommend.tsx
  app/(tabs)/music-recommend/searchMusic.tsx
  app/(tabs)/music-recommend/sendRecommend.tsx
  app/(tabs)/recommend-tab/RecShareModal.tsx
  hooks/useEditProfile.ts
Labels: Fix, Design, 이즈

#119 Fix/#117 chore
  api/replies.ts
  api/sentRecoms.ts
  app/(onboarding)/step2-artist.tsx
  app/(tabs)/home.tsx
  app/(tabs)/music-recommend/myRecommend.tsx
  app/(tabs)/myPage/setting/interestedArtists.tsx
  app/(tabs)/recommend-tab/RecommendCal.tsx
  app/(tabs)/recommend.tsx
  components/common/InterestedArtistList.tsx
  package.json
  yarn.lock
Labels: Fix, API, 오즈

#122 FIX: 아티스트 채널 배경 이미지, UI 오류 수정
  app/(tabs)/music-recommend/myRecommend.tsx
  app/artist/[artistId].tsx
Labels: Design, 무니

#129 FIX: 로그인 없이 둘러보기 시 토큰 다 뺌
  app/(auth)/splash.tsx
Labels: Fix, API, 이즈

#130 FIX: 타이머 사용자 설정으로 변경
  api/sentRecoms.ts
  app/(tabs)/music-recommend/myRecommend.tsx
  app/(tabs)/recommend-tab/RecShareModal.tsx
Labels: Fix, 무니
