Repository Bandnol/Bandnol-Front, pull requests merged in 2025-07, with the labels that each got.

#4 Feat/#2 music recommend UI
  .github/pull_request_template.md
  .prettierrc
  .vscode/settings.json
  app/(tabs)/_layout.tsx
  app/(tabs)/artist.tsx
  app/(tabs)/explore.tsx
  app/(tabs)/home.tsx
  app/(tabs)/index.tsx
  app/(tabs)/music-recommend/alarmCenter.tsx
  app/(tabs)/music-recommend/myRecommend.tsx
  app/(tabs)/music-recommend/receiveRecommend.tsx
  app/(tabs)/music-recommend/searchMusic.tsx
  app/(tabs)/music-recommend/sendRecommend.tsx
  app/(tabs)/mypage.tsx
  app/(tabs)/recommend.tsx
  app/(tabs)/setting.tsx
  app/_layout.tsx
  app/index.tsx
  assets/images/Bandnol-logo.png
  assets/images/ai-comment.png
  assets/images/alarm.png
  assets/images/album-cover.jpg
  assets/images/alert.png
  assets/images/backarrow.png
  assets/images/checkbox.png
  assets/images/comment.png
  assets/images/error.png
  assets/images/like.png
  assets/images/play.png
  assets/images/search.png
  assets/images/unlike.png
  babel.config.js
  components/common/BottomTabBar.tsx
  components/common/DateHeader.tsx
  components/common/types.ts
  metro.config.js
  package-lock.json
  package.json
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: Feature, 무니

#13 FIX/#11 하단바 아이콘 및 정렬 수정
  components/common/BottomTabBar.tsx
  components/common/icons/Home-active.svg
  components/common/icons/Home-inactive.svg
  components/common/icons/MyPage-active.svg
  components/common/icons/MyPage-inactive.svg
  components/common/icons/Post-active.svg
  components/common/icons/Post-inactive.svg
  components/common/icons/Recommend-active.svg
  components/common/icons/Recommend-inactive.svg
Labels: Fix, 이즈

#17 UI/#12 notification center
  app/(tabs)/music-recommend/alarmCenter.tsx
  app/(tabs)/setting.tsx
  assets/icons/size_l/icon=alert.svg
  assets/icons/size_l/icon=bookmark.svg
  assets/icons/size_l/icon=exclamationmark-square-fill.svg
  assets/icons/size_l/icon=exclamationmark-square.svg
  assets/icons/size_l/icon=heart.svg
  assets/icons/size_l/icon=message.svg
  assets/icons/size_l/icon=report.svg
  assets/icons/size_l/icon=sad.svg
  assets/icons/size_l/icon=song.svg
  assets/icons/size_l/icon=thumbsup.svg
  assets/icons/size_m/backarrow.svg
  components/NotificationIcon.tsx
  components/NotificationItem.tsx
  constants/notifications.ts
  package-lock.json
  package.json
  types/svg.d.ts
  yarn.lock
Labels: Design, 보현

#26 UI/#18 recommend tab
  .github/ISSUE_TEMPLATE/--bug-template.md
  .github/ISSUE_TEMPLATE/--feature-template.md
  .github/ISSUE_TEMPLATE/--pr-template.md
  README.md
  app/(tabs)/music-recommend/alarmCenter.tsx
  app/(tabs)/recommend-tab/RecBottomModal.tsx
  app/(tabs)/recommend-tab/RecSearch.tsx
  app/(tabs)/recommend-tab/RecShareModal.tsx
  app/(tabs)/recommend-tab/RecommendCal.tsx
  app/(tabs)/recommend-tab/RecommendHeader.tsx
  app/(tabs)/recommend-tab/RecommendList.tsx
  app/(tabs)/recommend.tsx
  assets/icons/size_m/calendar.svg
  assets/icons/size_m/dropdown.svg
  assets/icons/size_m/insta.svg
  assets/icons/size_m/link.svg
  assets/icons/size_m/list.svg
  assets/icons/size_m/quit.svg
  assets/icons/size_m/report.svg
  assets/icons/size_m/search.svg
  assets/icons/size_m/share.svg
  assets/icons/size_m/x.svg
  components/Caltestdata.ts
  components/Listtestdata.ts
  components/MonthPicker.tsx
  components/NotificationItem.tsx
  components/WheelList.tsx
  components/common/BottomTabBar.tsx
  package-lock.json
  package.json
  yarn.lock
Labels: Feature, 보현

#19 UI/#16 마이페이지, 설정 UI 구현
  app/(tabs)/myPage/editProfile.tsx
  app/(tabs)/myPage/follow-status/followEachOther.tsx
  app/(tabs)/myPage/follow-status/followedByOther.tsx
  app/(tabs)/myPage/follow-status/followingOnlyOther.tsx
  app/(tabs)/myPage/follow-status/notFollowingEachOther.tsx
  app/(tabs)/myPage/followPage.tsx
  app/(tabs)/myPage/myPage.tsx
  app/(tabs)/myPage/myPageSearch.tsx
  app/(tabs)/myPage/setting/appSetting.tsx
  app/(tabs)/myPage/setting/notification.tsx
  app/(tabs)/myPage/setting/receiveTime.tsx
  app/(tabs)/myPage/setting/termsOfService.tsx
  app/(tabs)/myPage/setting/userInfo.tsx
  app/(tabs)/mypage.tsx
  assets/icons/bookmark-fill.svg
  assets/icons/bookmark.svg
  assets/icons/clip.svg
  assets/icons/close.svg
  assets/icons/delete.svg
  assets/icons/edit.svg
  assets/icons/heart.svg
  assets/icons/more.svg
  assets/icons/setting.svg
  assets/icons/share.svg
  assets/icons/write.svg
  assets/images/background.png
  assets/images/dummy1.png
  assets/images/profile-background.jpg
  assets/images/profile.png
  assets/images/white.jpg
  package-lock.json
  package.json
  yarn.lock
Labels: Design, 이즈

#32 Fix/#31 setting router
  app/(tabs)/setting.tsx
  yarn.lock
Labels: Fix, 이즈
